RIME_BASE      = packetbuf.c queuebuf.c rimeaddr.c ctimer.c packetqueue.c

ifdef UIP_CONF_IPV6
RIME_UIP6      = rime-udp.c
endif # UIP_CONF_IPV6

CONTIKI_SOURCEFILES += $(RIME_BASE) \
               $(RIME_UIP6)
